/**
 * generated by Xtext 2.13.0
 */
package org.palladiosimulator.qes.ui.labeling;

import com.google.inject.Inject;
import javax.annotation.Generated;
import org.eclipse.emf.edit.ui.provider.AdapterFactoryLabelProvider;
import org.eclipse.xtext.ui.label.DefaultEObjectLabelProvider;

/**
 * Provides labels for EObjects.
 * 
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#label-provider
 */
@SuppressWarnings("all")
@Generated("org.eclipse.xtend.core.compiler.XtendGenerator")
public class QualityEffectSpecificationLabelProvider extends DefaultEObjectLabelProvider {
  @Inject
  public QualityEffectSpecificationLabelProvider(final AdapterFactoryLabelProvider delegate) {
    super(delegate);
  }
}
