/*
 * generated by Xtext 2.13.0
 */
package org.palladiosimulator.aes.ui;

import com.google.inject.Injector;
import org.eclipse.core.runtime.Platform;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.palladiosimulator.aes.ui.internal.AesActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class ArchitectureEffectSpecificationExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return Platform.getBundle(AesActivator.PLUGIN_ID);
	}
	
	@Override
	protected Injector getInjector() {
		AesActivator activator = AesActivator.getInstance();
		return activator != null ? activator.getInjector(AesActivator.ORG_PALLADIOSIMULATOR_AES_ARCHITECTUREEFFECTSPECIFICATION) : null;
	}

}
