/*
 * generated by Xtext 2.14.0
 */
package edu.kit.ipd.are.dsexplore.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractFcDslScopeProvider extends DelegatingScopeProvider {
}
