<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="featureSolution" nsURI="http://are.ipd.kit.edu/FeatureSolutionModel/1.0.0"
    nsPrefix="featureSolution">
  <eClassifiers xsi:type="ecore:EClass" name="InclusionMechanism" abstract="true"
      eSuperTypes="featureCompletions.ecore#//DescribedElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="multiple" eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AdapterInclusion" eSuperTypes="#//InclusionMechanism">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="appears" lowerBound="1"
        eType="#//Appearance" defaultValueLiteral="BEFORE"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ExtensionInclusion" eSuperTypes="#//InclusionMechanism">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="appears" lowerBound="1"
        eType="#//Appearance" defaultValueLiteral="BEFORE"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="placementStrategy" upperBound="-1"
        eType="#//PlacementStrategy" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Appearance">
    <eLiterals name="BEFORE"/>
    <eLiterals name="AFTER" value="1"/>
    <eLiterals name="AROUND" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="PlacementPolicy">
    <eLiterals name="MANDATORY" literal="MANDATORY"/>
    <eLiterals name="OBLIGATORY" value="1" literal="OBLIGATORY"/>
    <eLiterals name="PROHIBITED" value="2" literal="PROHIBITED"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PlacementStrategy"/>
  <eClassifiers xsi:type="ecore:EClass" name="ExternalCallPlacementStrategy" eSuperTypes="#//PlacementStrategy">
    <eStructuralFeatures xsi:type="ecore:EReference" name="matchingSignature" eType="ecore:EClass ../../org.palladiosimulator.pcm/model/pcm.ecore#//repository/Signature"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InternalActionPlacementStrategy" eSuperTypes="#//PlacementStrategy">
    <eStructuralFeatures xsi:type="ecore:EReference" name="matchingInternalAction"
        eType="ecore:EClass ../../org.palladiosimulator.pcm/model/pcm.ecore#//seff/InternalAction"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ControlFlowPlacementStrategy" eSuperTypes="#//PlacementStrategy">
    <eStructuralFeatures xsi:type="ecore:EReference" name="matchingControlFlow" eType="ecore:EClass ../../org.palladiosimulator.pcm/model/pcm.ecore#//seff/AbstractLoopAction"/>
  </eClassifiers>
</ecore:EPackage>
