/**
 * generated by Xtext 2.13.0
 */
package org.palladiosimulator.aes.architectureEffectSpecification;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.palladiosimulator.aes.architectureEffectSpecification.ArchitectureEffectSpecificationFactory
 * @model kind="package"
 * @generated
 */
public interface ArchitectureEffectSpecificationPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "architectureEffectSpecification";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.palladiosimulator.org/aes/ArchitectureEffectSpecification";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "architectureEffectSpecification";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  ArchitectureEffectSpecificationPackage eINSTANCE = org.palladiosimulator.aes.architectureEffectSpecification.impl.ArchitectureEffectSpecificationPackageImpl.init();

  /**
   * The meta object id for the '{@link org.palladiosimulator.aes.architectureEffectSpecification.impl.ModelImpl <em>Model</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.palladiosimulator.aes.architectureEffectSpecification.impl.ModelImpl
   * @see org.palladiosimulator.aes.architectureEffectSpecification.impl.ArchitectureEffectSpecificationPackageImpl#getModel()
   * @generated
   */
  int MODEL = 0;

  /**
   * The feature id for the '<em><b>Elements</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__ELEMENTS = 0;

  /**
   * The number of structural features of the '<em>Model</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.palladiosimulator.aes.architectureEffectSpecification.impl.FindByNameImpl <em>Find By Name</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.palladiosimulator.aes.architectureEffectSpecification.impl.FindByNameImpl
   * @see org.palladiosimulator.aes.architectureEffectSpecification.impl.ArchitectureEffectSpecificationPackageImpl#getFindByName()
   * @generated
   */
  int FIND_BY_NAME = 1;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FIND_BY_NAME__NAME = 0;

  /**
   * The number of structural features of the '<em>Find By Name</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FIND_BY_NAME_FEATURE_COUNT = 1;


  /**
   * Returns the meta object for class '{@link org.palladiosimulator.aes.architectureEffectSpecification.Model <em>Model</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Model</em>'.
   * @see org.palladiosimulator.aes.architectureEffectSpecification.Model
   * @generated
   */
  EClass getModel();

  /**
   * Returns the meta object for the containment reference list '{@link org.palladiosimulator.aes.architectureEffectSpecification.Model#getElements <em>Elements</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Elements</em>'.
   * @see org.palladiosimulator.aes.architectureEffectSpecification.Model#getElements()
   * @see #getModel()
   * @generated
   */
  EReference getModel_Elements();

  /**
   * Returns the meta object for class '{@link org.palladiosimulator.aes.architectureEffectSpecification.FindByName <em>Find By Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Find By Name</em>'.
   * @see org.palladiosimulator.aes.architectureEffectSpecification.FindByName
   * @generated
   */
  EClass getFindByName();

  /**
   * Returns the meta object for the attribute '{@link org.palladiosimulator.aes.architectureEffectSpecification.FindByName#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.palladiosimulator.aes.architectureEffectSpecification.FindByName#getName()
   * @see #getFindByName()
   * @generated
   */
  EAttribute getFindByName_Name();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  ArchitectureEffectSpecificationFactory getArchitectureEffectSpecificationFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.palladiosimulator.aes.architectureEffectSpecification.impl.ModelImpl <em>Model</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.palladiosimulator.aes.architectureEffectSpecification.impl.ModelImpl
     * @see org.palladiosimulator.aes.architectureEffectSpecification.impl.ArchitectureEffectSpecificationPackageImpl#getModel()
     * @generated
     */
    EClass MODEL = eINSTANCE.getModel();

    /**
     * The meta object literal for the '<em><b>Elements</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODEL__ELEMENTS = eINSTANCE.getModel_Elements();

    /**
     * The meta object literal for the '{@link org.palladiosimulator.aes.architectureEffectSpecification.impl.FindByNameImpl <em>Find By Name</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.palladiosimulator.aes.architectureEffectSpecification.impl.FindByNameImpl
     * @see org.palladiosimulator.aes.architectureEffectSpecification.impl.ArchitectureEffectSpecificationPackageImpl#getFindByName()
     * @generated
     */
    EClass FIND_BY_NAME = eINSTANCE.getFindByName();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute FIND_BY_NAME__NAME = eINSTANCE.getFindByName_Name();

  }

} //ArchitectureEffectSpecificationPackage
