<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="SolutionModel" nsURI="http://are.ipd.kit.edu/SolutionModel/1.0.0"
    nsPrefix="Solution">
  <eClassifiers xsi:type="ecore:EClass" name="Solution">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="repository" lowerBound="1"
        eType="ecore:EClass platform:/plugin/org.palladiosimulator.pcm/model/pcm.ecore#//repository/Repository"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="costRepository" eType="ecore:EClass platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EObject"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SolutionRepository">
    <eStructuralFeatures xsi:type="ecore:EReference" name="solutions" upperBound="-1"
        eType="#//Solution" containment="true"/>
  </eClassifiers>
</ecore:EPackage>
