<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="TransformationModel" nsURI="http://are.ipd.kit.edu/TransformationModel/1.0.0"
    nsPrefix="TransformationModel">
  <eClassifiers xsi:type="ecore:EClass" name="Transformation" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="threshold" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="0"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="multiple" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="injectable" lowerBound="1"
        eType="ecore:EClass concerns.ecore#//AnnotationEnrich"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
        eType="ecore:EClass concerns.ecore#//AnnotationTarget"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TransformationRepository">
    <eStructuralFeatures xsi:type="ecore:EReference" name="transformation" upperBound="-1"
        eType="#//Transformation" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ExtensionTransformation" eSuperTypes="#//Transformation"/>
  <eClassifiers xsi:type="ecore:EClass" name="AdapterTransformation" eSuperTypes="#//Transformation">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="appear" eType="#//Appearance"
        defaultValueLiteral="BEFORE"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Appearance">
    <eLiterals name="BEFORE"/>
    <eLiterals name="AFTER" value="1"/>
    <eLiterals name="AROUND" value="2"/>
  </eClassifiers>
</ecore:EPackage>
