/**
 * generated by Xtext 2.14.0
 */
package org.palladiosimulator.qes.validation;

import org.palladiosimulator.qes.validation.AbstractQualityEffectSpecificationValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class QualityEffectSpecificationValidator extends AbstractQualityEffectSpecificationValidator {
}
