/*
 * generated by Xtext 2.24.0
 */
package edu.kit.ipd.are.dsexplore.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.validation.AbstractDeclarativeValidator;

public abstract class AbstractFcDslValidator extends AbstractDeclarativeValidator {
	
	@Override
	protected List<EPackage> getEPackages() {
		List<EPackage> result = new ArrayList<EPackage>();
		result.add(EPackage.Registry.INSTANCE.getEPackage("http://are.ipd.kit.edu/FeatureSolutionModel/1.0.0"));
		result.add(EPackage.Registry.INSTANCE.getEPackage("http://are.ipd.kit.edu/PlacementDescriptionModel/1.0.0"));
		return result;
	}
}
