<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="cost"
    nsURI="http://sdq.ipd.uka.de/CostModel/1.0" nsPrefix="cost">
  <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
    <details key="documentation" value="The CostModel metamodel represents the cost of a software architecture and its alternatives. &#xD;&#xA;&#xD;&#xA;So far, the main concepts are ComponentCost and FixedProcessingResourceCost. ComponentCost specify how much is added to the software architecture cost if the referenced component is used. FixedProcessingResourceCost specify how much is added to the overall cost if the server that contains the referenced ProcessingResourceSpecification (e.g. a CPU with speed 1GHz) is used. &#xD;&#xA;&#xD;&#xA;Thus, to determine the overall cost of one candidate solution (i.e. one architecture), we need to check the PCM model to see which components and servers are used. We might want to add more classes to the taskmodel to make this easier. &#xD;&#xA;&#xD;&#xA;See the Cost element for details on the use of this model. "/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="ComponentCost" eSuperTypes="#//Cost">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="&lt;p>&#xD;&#xA;    For&amp;nbsp;components,&amp;nbsp;the&amp;nbsp;componentOperatingCost&amp;nbsp;and&amp;nbsp;componentInitialCost&amp;nbsp;are&amp;nbsp;directly&amp;nbsp;specified&amp;nbsp;and&amp;nbsp;are&amp;nbsp;used&amp;nbsp;to&amp;nbsp;derive&amp;nbsp;the&amp;nbsp;operatingCost&amp;nbsp;and&amp;nbsp;the&amp;nbsp;initialCost&amp;nbsp;1:1.&amp;nbsp;&#xD;&#xA;&lt;/p>&#xD;&#xA;&lt;p>&#xD;&#xA;    ComponentCostPerType occur once for each component in the repository that is used in the system to analyse, regardless&#xD;&#xA;    of how often the component is instantiated (in AssemblyContexts or AllocationContexts).&#xD;&#xA;&lt;/p>"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="componentOperatingCost"
        ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="componentInitialCost" ordered="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="repositoryComponent" ordered="false"
        lowerBound="1" eType="ecore:EClass ../../de.uka.ipd.sdq.pcm/model/pcm.ecore#//repository/RepositoryComponent"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Cost" abstract="true">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="This class represents the cost of an Entity. The definition of the cost is deferred to the subclasses that have to define the value of the derived attribute. &#xD;&#xA;&#xD;&#xA;When using the Cost, you can read the initialCost to get the procurement cost for the system. The operating cost reflect cost to operate the system over time. Using the present value formula, both cost can be combined to total cost of ownership. "/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="annotatedElement" ordered="false"
        lowerBound="1" eType="ecore:EClass platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EObject"
        changeable="false" volatile="true" transient="true" unsettable="true" derived="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="suppressedIsSetVisibility" value="true"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="operatingCost" ordered="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"
        changeable="false" volatile="true" transient="true" derived="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The value of this attributes has to be derived in subclasses. "/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="initialCost" ordered="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"
        changeable="false" volatile="true" transient="true" derived="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FixedLinkingResourceCost" eSuperTypes="#//LinkingResourceCost #//Cost"/>
  <eClassifiers xsi:type="ecore:EClass" name="LinkingResourceCost" abstract="true"
      eSuperTypes="#//Cost">
    <eStructuralFeatures xsi:type="ecore:EReference" name="linkingresource" ordered="false"
        lowerBound="1" eType="ecore:EClass ../../de.uka.ipd.sdq.pcm/model/pcm.ecore#//resourceenvironment/LinkingResource"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FixedProcessingResourceCost" eSuperTypes="#//ProcessingResourceCost #//Cost">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="For servers in the resource environemnt, cost can also be directly specified with the FixedProcessingResourceCost. The fixedOperatingCost and fixedInitialCost are directly specified and are used to derive the operatingCost and the initialCost 1:1. &#xD;&#xA;&#xD;&#xA;TODO: need additional repository of available resource &quot;subtypes&quot;. "/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fixedOperatingCost" ordered="false"
        lowerBound="1" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fixedInitialCost" ordered="false"
        lowerBound="1" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EDouble"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ProcessingResourceCost" abstract="true"
      eSuperTypes="#//Cost">
    <eStructuralFeatures xsi:type="ecore:EReference" name="processingresourcespecification"
        ordered="false" lowerBound="1" eType="ecore:EClass ../../de.uka.ipd.sdq.pcm/model/pcm.ecore#//resourceenvironment/ProcessingResourceSpecification"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VariableCost" abstract="true" eSuperTypes="#//Cost">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fixedInitialCost" ordered="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fixedOperatingCost" ordered="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VariableLinkingResourceCost" eSuperTypes="#//VariableCost #//LinkingResourceCost">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="see VariableProcessingResourceCost, this one works analogously. "/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="bandwithInitialFactor"
        ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="bandwidthOperatingFactor"
        ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VariableProcessingResourceCost" eSuperTypes="#//VariableCost #//ProcessingResourceCost">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="VariableProcessingResourceCost are attached to ProcessingResourceSpecification. They derive the operating cost and inital cost based on the processingRate of the resource, as defined in the processing rate (operating or initial) cost function. Use the variable procRate.VALUE to refer to the processing rate in the expression. Additionally, the fixed initial costs as specified in VariableCost are added to the respective cost.&#xD;&#xA;&#xD;&#xA;"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="processingRateInitialFunction"
        ordered="false" lowerBound="1" eType="#//ScalarFunction" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="processingRateOperatingFunction"
        ordered="false" lowerBound="1" eType="#//ScalarFunction" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ScalarFunction">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="specification" ordered="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="term" ordered="false" lowerBound="1"
        eType="ecore:EClass platform:/plugin/de.uka.ipd.sdq.stoex/model/stoex.ecore#//Term"
        changeable="false" volatile="true" transient="true" unsettable="true" derived="true">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="namespace" value=""/>
      </eAnnotations>
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="suppressedIsSetVisibility" value="true"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CostRepository">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="The cost repository is the root element of the cost model. It contains all costs for a PCM instance and for the different design alternatives. &#xD;&#xA;&#xD;&#xA;If we have FixedProcessingResourceCost for certain types of, for example, CPUs, we have to check the model first which annotated elements are actually used. Same with alternative components. Only used elements lead to overall cost of the system. "/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="cost" ordered="false" upperBound="-1"
        eType="#//Cost" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="timePeriodYears" ordered="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Time period in which the operating costs are expected."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="interest" ordered="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="&lt;p>&#xD;&#xA;    Assumed&amp;nbsp;interest&amp;nbsp;rate&amp;nbsp;per&amp;nbsp;year for calculating the present value based on the operating costs and&#xD;&#xA;    the considered time frame in years given by timePeriodYears.&#xD;&#xA;&lt;/p>"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ComponentCostPerInstance" eSuperTypes="#//ComponentCost">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="ComponentCostPerInstance are also costs for components; however, they occur per instance of the referenced components. The&#xD;&#xA;referenced Allocation is used to determine the number of instances of the component, which is multiplied by the costs per&#xD;&#xA;instance."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="allocation" ordered="false"
        eType="ecore:EClass ../../de.uka.ipd.sdq.pcm/model/pcm.ecore#//allocation/Allocation"/>
  </eClassifiers>
</ecore:EPackage>
