/*
 * generated by Xtext 2.14.0
 */
package org.palladiosimulator.qes.ide


/**
 * Use this class to register ide components.
 */
class QualityEffectSpecificationIdeModule extends AbstractQualityEffectSpecificationIdeModule {
}
