/**
 * generated by Xtext 2.14.0
 */
package org.palladiosimulator.qes.ui;

import javax.annotation.Generated;
import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;
import org.palladiosimulator.qes.ui.AbstractQualityEffectSpecificationUiModule;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
@Generated("org.eclipse.xtend.core.compiler.XtendGenerator")
public class QualityEffectSpecificationUiModule extends AbstractQualityEffectSpecificationUiModule {
  public QualityEffectSpecificationUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
