/**
 * generated by Xtext 2.13.0
 */
package org.palladiosimulator.aes.architectureEffectSpecification.impl;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

import org.eclipse.emf.ecore.impl.EPackageImpl;

import org.palladiosimulator.aes.architectureEffectSpecification.ArchitectureEffectSpecificationFactory;
import org.palladiosimulator.aes.architectureEffectSpecification.ArchitectureEffectSpecificationPackage;
import org.palladiosimulator.aes.architectureEffectSpecification.FindByName;
import org.palladiosimulator.aes.architectureEffectSpecification.Model;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model <b>Package</b>.
 * <!-- end-user-doc -->
 * @generated
 */
public class ArchitectureEffectSpecificationPackageImpl extends EPackageImpl implements ArchitectureEffectSpecificationPackage
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass modelEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass findByNameEClass = null;

  /**
   * Creates an instance of the model <b>Package</b>, registered with
   * {@link org.eclipse.emf.ecore.EPackage.Registry EPackage.Registry} by the package
   * package URI value.
   * <p>Note: the correct way to create the package is via the static
   * factory method {@link #init init()}, which also performs
   * initialization of the package, or returns the registered package,
   * if one already exists.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.eclipse.emf.ecore.EPackage.Registry
   * @see org.palladiosimulator.aes.architectureEffectSpecification.ArchitectureEffectSpecificationPackage#eNS_URI
   * @see #init()
   * @generated
   */
  private ArchitectureEffectSpecificationPackageImpl()
  {
    super(eNS_URI, ArchitectureEffectSpecificationFactory.eINSTANCE);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private static boolean isInited = false;

  /**
   * Creates, registers, and initializes the <b>Package</b> for this model, and for any others upon which it depends.
   * 
   * <p>This method is used to initialize {@link ArchitectureEffectSpecificationPackage#eINSTANCE} when that field is accessed.
   * Clients should not invoke it directly. Instead, they should simply access that field to obtain the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #eNS_URI
   * @see #createPackageContents()
   * @see #initializePackageContents()
   * @generated
   */
  public static ArchitectureEffectSpecificationPackage init()
  {
    if (isInited) return (ArchitectureEffectSpecificationPackage)EPackage.Registry.INSTANCE.getEPackage(ArchitectureEffectSpecificationPackage.eNS_URI);

    // Obtain or create and register package
    ArchitectureEffectSpecificationPackageImpl theArchitectureEffectSpecificationPackage = (ArchitectureEffectSpecificationPackageImpl)(EPackage.Registry.INSTANCE.get(eNS_URI) instanceof ArchitectureEffectSpecificationPackageImpl ? EPackage.Registry.INSTANCE.get(eNS_URI) : new ArchitectureEffectSpecificationPackageImpl());

    isInited = true;

    // Create package meta-data objects
    theArchitectureEffectSpecificationPackage.createPackageContents();

    // Initialize created meta-data
    theArchitectureEffectSpecificationPackage.initializePackageContents();

    // Mark meta-data to indicate it can't be changed
    theArchitectureEffectSpecificationPackage.freeze();

  
    // Update the registry and return the package
    EPackage.Registry.INSTANCE.put(ArchitectureEffectSpecificationPackage.eNS_URI, theArchitectureEffectSpecificationPackage);
    return theArchitectureEffectSpecificationPackage;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getModel()
  {
    return modelEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getModel_Elements()
  {
    return (EReference)modelEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getFindByName()
  {
    return findByNameEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getFindByName_Name()
  {
    return (EAttribute)findByNameEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public ArchitectureEffectSpecificationFactory getArchitectureEffectSpecificationFactory()
  {
    return (ArchitectureEffectSpecificationFactory)getEFactoryInstance();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private boolean isCreated = false;

  /**
   * Creates the meta-model objects for the package.  This method is
   * guarded to have no affect on any invocation but its first.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void createPackageContents()
  {
    if (isCreated) return;
    isCreated = true;

    // Create classes and their features
    modelEClass = createEClass(MODEL);
    createEReference(modelEClass, MODEL__ELEMENTS);

    findByNameEClass = createEClass(FIND_BY_NAME);
    createEAttribute(findByNameEClass, FIND_BY_NAME__NAME);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private boolean isInitialized = false;

  /**
   * Complete the initialization of the package and its meta-model.  This
   * method is guarded to have no affect on any invocation but its first.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void initializePackageContents()
  {
    if (isInitialized) return;
    isInitialized = true;

    // Initialize package
    setName(eNAME);
    setNsPrefix(eNS_PREFIX);
    setNsURI(eNS_URI);

    // Create type parameters

    // Set bounds for type parameters

    // Add supertypes to classes

    // Initialize classes and features; add operations and parameters
    initEClass(modelEClass, Model.class, "Model", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getModel_Elements(), this.getFindByName(), null, "elements", null, 0, -1, Model.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(findByNameEClass, FindByName.class, "FindByName", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getFindByName_Name(), ecorePackage.getEString(), "name", null, 0, 1, FindByName.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    // Create resource
    createResource(eNS_URI);
  }

} //ArchitectureEffectSpecificationPackageImpl
