/**
 * generated by Xtext 2.13.0
 */
package org.palladiosimulator.qes.qualityEffectSpecification.impl;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;

import org.eclipse.emf.ecore.impl.EFactoryImpl;

import org.eclipse.emf.ecore.plugin.EcorePlugin;

import org.palladiosimulator.qes.qualityEffectSpecification.*;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model <b>Factory</b>.
 * <!-- end-user-doc -->
 * @generated
 */
public class QualityEffectSpecificationFactoryImpl extends EFactoryImpl implements QualityEffectSpecificationFactory
{
  /**
   * Creates the default factory implementation.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public static QualityEffectSpecificationFactory init()
  {
    try
    {
      QualityEffectSpecificationFactory theQualityEffectSpecificationFactory = (QualityEffectSpecificationFactory)EPackage.Registry.INSTANCE.getEFactory(QualityEffectSpecificationPackage.eNS_URI);
      if (theQualityEffectSpecificationFactory != null)
      {
        return theQualityEffectSpecificationFactory;
      }
    }
    catch (Exception exception)
    {
      EcorePlugin.INSTANCE.log(exception);
    }
    return new QualityEffectSpecificationFactoryImpl();
  }

  /**
   * Creates an instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public QualityEffectSpecificationFactoryImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EObject create(EClass eClass)
  {
    switch (eClass.getClassifierID())
    {
      case QualityEffectSpecificationPackage.MODEL: return createModel();
      case QualityEffectSpecificationPackage.FIND_BY_NAME: return createFindByName();
      default:
        throw new IllegalArgumentException("The class '" + eClass.getName() + "' is not a valid classifier");
    }
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Model createModel()
  {
    ModelImpl model = new ModelImpl();
    return model;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public FindByName createFindByName()
  {
    FindByNameImpl findByName = new FindByNameImpl();
    return findByName;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public QualityEffectSpecificationPackage getQualityEffectSpecificationPackage()
  {
    return (QualityEffectSpecificationPackage)getEPackage();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @deprecated
   * @generated
   */
  @Deprecated
  public static QualityEffectSpecificationPackage getPackage()
  {
    return QualityEffectSpecificationPackage.eINSTANCE;
  }

} //QualityEffectSpecificationFactoryImpl
