/**
 * generated by Xtext 2.14.0
 */
package org.palladiosimulator.qes.qualityEffectSpecification.impl;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.palladiosimulator.qes.qualityEffectSpecification.QualityEffectSpecificationPackage;
import org.palladiosimulator.qes.qualityEffectSpecification.ResourceProperty;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Resource Property</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class ResourcePropertyImpl extends MinimalEObjectImpl.Container implements ResourceProperty
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ResourcePropertyImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return QualityEffectSpecificationPackage.Literals.RESOURCE_PROPERTY;
  }

} //ResourcePropertyImpl
