/**
 * generated by Xtext 2.14.0
 */
package org.palladiosimulator.qes.qualityEffectSpecification.impl;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.palladiosimulator.qes.qualityEffectSpecification.QualityEffectSpecificationPackage;
import org.palladiosimulator.qes.qualityEffectSpecification.TransformationSpecification;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Transformation Specification</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class TransformationSpecificationImpl extends MinimalEObjectImpl.Container implements TransformationSpecification
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected TransformationSpecificationImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return QualityEffectSpecificationPackage.Literals.TRANSFORMATION_SPECIFICATION;
  }

} //TransformationSpecificationImpl
