/*
 * generated by Xtext 2.13.0
 */
package org.palladiosimulator.qes.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractQualityEffectSpecificationScopeProvider extends DelegatingScopeProvider {
}
