<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="componentSecurity" nsURI="http://www.example.org/componentSecurity"
    nsPrefix="componentSecurity">
  <eClassifiers xsi:type="ecore:EClass" name="ComponentSecurity">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="poCoB" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"
        defaultValueLiteral="0.2"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="TTDV" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"
        defaultValueLiteral="200.0"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ComponentSecurityRepository">
    <eStructuralFeatures xsi:type="ecore:EReference" name="componentsecurity" upperBound="-1"
        eType="#//ComponentSecurity" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SecurityTarget"/>
</ecore:EPackage>
