<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="taskmodel"
    nsURI="http://sdq.ipd.uka.de/TaskModel/1.0" nsPrefix="taskmodel">
  <eClassifiers xsi:type="ecore:EClass" name="Task">
    <eOperations name="sumOfProbabilitiesMustBeOne" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="self.edge_Task->collect(e|e.transitionProbability)->sum()=1 or self.edge_Task->isEmpty() "/>
      </eAnnotations>
      <eParameters name="diagnostics" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDiagnosticChain"/>
      <eParameters name="context" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EMap"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" ordered="false" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" changeable="false"
        volatile="true" transient="true" unsettable="true" derived="true">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="namespace" value=""/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="probabilityOfExecution"
        ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="failureProbability" ordered="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="meanDemandedTime" ordered="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="repositorycomponent" ordered="false"
        lowerBound="1" eType="ecore:EClass pcm.ecore#//repository/RepositoryComponent"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="allocationcontext" ordered="false"
        eType="ecore:EClass pcm.ecore#//allocation/AllocationContext"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="edge_Task" ordered="false"
        upperBound="-1" eType="#//Edge" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="abstractaction" ordered="false"
        eType="ecore:EClass pcm.ecore#//seff/AbstractAction"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Edge">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="transitionProbability"
        ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="successor_Edge" ordered="false"
        lowerBound="1" eType="#//Task"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TaskList">
    <eStructuralFeatures xsi:type="ecore:EReference" name="task_TaskList" ordered="false"
        upperBound="-1" eType="#//Task" containment="true"/>
  </eClassifiers>
</ecore:EPackage>
