/**
 *
 * $Id$
 */
package de.uka.ipd.sdq.dsexplore.qml.contract.validation;

import de.uka.ipd.sdq.dsexplore.qml.contract.EvaluationAspect;

import de.uka.ipd.sdq.dsexplore.qml.dimensions.Dimension;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link de.uka.ipd.sdq.dsexplore.qml.contract.Criterion}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface CriterionValidator {
	boolean validate();

	boolean validateDimension(Dimension value);
	boolean validateAspects(EList<EvaluationAspect> value);
}
