/**
 *
 * $Id$
 */
package de.uka.ipd.sdq.dsexplore.qml.contract.validation;

import de.uka.ipd.sdq.dsexplore.qml.contract.RangeValue;

/**
 * A sample validator interface for {@link de.uka.ipd.sdq.dsexplore.qml.contract.Frequency}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface FrequencyValidator {
	boolean validate();

	boolean validateUpperLimit(RangeValue value);
	boolean validateLowerLimit(RangeValue value);
}
