/**
 * generated by Xtext 2.13.0
 */
package org.palladiosimulator.qes.ide;

import org.palladiosimulator.qes.ide.AbstractQualityEffectSpecificationIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class QualityEffectSpecificationIdeModule extends AbstractQualityEffectSpecificationIdeModule {
}
