/**
 *
 * $Id$
 */
package de.uka.ipd.sdq.nqr.validation;

import de.uka.ipd.sdq.dsexplore.qml.contract.Criterion;

import org.eclipse.emf.common.util.EList;

import org.palladiosimulator.pcm.repository.RepositoryComponent;

/**
 * A sample validator interface for {@link de.uka.ipd.sdq.nqr.Nqr}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface NqrValidator {
	boolean validate();

	boolean validateAnnotatedElement(RepositoryComponent value);
	boolean validateCriterion(EList<Criterion> value);
}
