/*
 * generated by Xtext 2.13.0
 */
package org.palladiosimulator.aes.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.palladiosimulator.aes.parser.antlr.internal.InternalArchitectureEffectSpecificationParser;
import org.palladiosimulator.aes.services.ArchitectureEffectSpecificationGrammarAccess;

public class ArchitectureEffectSpecificationParser extends AbstractAntlrParser {

	@Inject
	private ArchitectureEffectSpecificationGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalArchitectureEffectSpecificationParser createParser(XtextTokenStream stream) {
		return new InternalArchitectureEffectSpecificationParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}

	public ArchitectureEffectSpecificationGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(ArchitectureEffectSpecificationGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
